" Автоскачивание vim-plug, если его нет
let data_dir = expand('~/.config/vim')
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


let mapleader = ' '

map w <Plug>CamelCaseMotion_w
map e <Plug>CamelCaseMotion_e
map b <Plug>CamelCaseMotion_b
map ge <Plug>CamelCaseMotion_ge

call plug#begin('~/.config/vim/plugged')

Plug 'bkad/CamelCaseMotion'

call plug#end()

noremap <Leader>y "*y
noremap <Leader>Y "*Y
noremap <Leader>p "*p
